In [2]:
import pandas as pd
import numpy as np

In [67]:
test = pd.read_csv('x_train.csv')
print(test['VOLUME_1'].isnull().sum())
R_In = list(range(17,24,2))
V_In = list(range(18,25,2))
test = test.dropna(subset = test.columns[R_In], how = 'all')
test = test.dropna(subset = test.columns[V_In], how = 'all')
print(test['VOLUME_1'].isnull().sum())

65025
10369

In [71]:
drp_ind=list(range(28,test.shape[1]))
test = test.drop(test.columns[drp_ind],axis = 1)

In [72]:
for i in range(1,10):
    test['RET_%d_diff' %i] = test['RET_%d' %i]-test['RET_%d' %(i+1)]
    test['VOLUME_%d_diff' %i] = test['VOLUME_%d' %i]-test['VOLUME_%d' %(i+1)]

In [73]:
new_features = []
shifts = range(1,10)  # Choose some different shifts\n",
statistics = ['mean']  # the type of stat\n",
gb_features = ['SECTOR', 'DATE']
target_feature_1 = 'RET'
target_feature_2 = 'diff'
tmp_name = '_'.join(gb_features)
for shift in shifts:
    for stat in statistics:
        name = f'{target_feature_1}_{shift}_{target_feature_2}_{tmp_name}_{stat}'
        feat = f'{target_feature_1}_{shift}_{target_feature_2}'
        new_features.append(name)
        for data in [test]:
            data[name] = data.groupby(gb_features)[feat].transform(stat)

In [74]:

new_features = []
shifts = range(1,10)  # Choose some different shifts\n",
statistics = ['mean']  # the type of stat\n",
gb_features = ['SECTOR', 'DATE']
target_feature_1 = 'VOLUME'
target_feature_2 = 'diff'
tmp_name = '_'.join(gb_features)
for shift in shifts:
    for stat in statistics:
        name = f'{target_feature_1}_{shift}_{target_feature_2}_{tmp_name}_{stat}'
        feat = f'{target_feature_1}_{shift}_{target_feature_2}'
        new_features.append(name)
        for data in [test]:
            data[name] = data.groupby(gb_features)[feat].transform(stat)

In [75]:
for ind in test.index:
    for i in range(9,0,-1):
        if pd.isnull(test['RET_%d' %i][ind]) and pd.notnull(test['RET_%d' %(i+1)][ind]):
            test['RET_%d' %i][ind] = test['RET_%d_diff_SECTOR_DATE_mean' %i][ind] + test['RET_%d' %(i+1)][ind]
for ind in test.index:
    for i in range(9,0,-1):
        if pd.isnull(test['VOLUME_%d' %i][ind]) and pd.notnull(test['VOLUME_%d' %(i+1)][ind]):
            test['VOLUME_%d' %i][ind] = test['VOLUME_%d_diff_SECTOR_DATE_mean' %i][ind] + test['VOLUME_%d' %(i+1)][ind]

/var/folders/28/fn5618590t1c1h5275yfw7mc0000gn/T/ipykernel_22332/38614170.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['RET_%d' %i][ind] = test['RET_%d_diff_SECTOR_DATE_mean' %i][ind] + test['RET_%d' %(i+1)][ind]
/var/folders/28/fn5618590t1c1h5275yfw7mc0000gn/T/ipykernel_22332/38614170.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['VOLUME_%d' %i][ind] = test['VOLUME_%d_diff_SECTOR_DATE_mean' %i][ind] + test['VOLUME_%d' %(i+1)][ind]

In [76]:
for ind in test.index:
    for i in range(1,10):
        if pd.isnull(test['RET_%d' %(i+1)][ind]) and pd.notnull(test['RET_%d' %(i)][ind]):
            test['RET_%d' %(i+1)][ind] = -test['RET_%d_diff_SECTOR_DATE_mean' %i][ind] + test['RET_%d' %(i)][ind]
for ind in test.index:
    for i in range(1,10):
        if pd.isnull(test['VOLUME_%d' %(i+1)][ind]) and pd.notnull(test['VOLUME_%d' %(i)][ind]):
            test['VOLUME_%d' %(i+1)][ind] = -test['VOLUME_%d_diff_SECTOR_DATE_mean' %i][ind] + test['VOLUME_%d' %(i)][ind]

/var/folders/28/fn5618590t1c1h5275yfw7mc0000gn/T/ipykernel_22332/1615727235.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['VOLUME_%d' %(i+1)][ind] = -test['VOLUME_%d_diff_SECTOR_DATE_mean' %i][ind] + test['VOLUME_%d' %(i)][ind]

In [83]:

drop_id = list(range(25,test.shape[1]))
data = data.drop(data.columns[drop_id], axis = 1)

,ID,DATE,STOCK,INDUSTRY,INDUSTRY_GROUP,SECTOR,SUB_INDUSTRY,RET_1,VOLUME_1,RET_2,...,RET_5,VOLUME_5,RET_6,VOLUME_6,RET_7,VOLUME_7,RET_8,VOLUME_8,RET_9,VOLUME_9
0,0,0,2,18,5,3,44,-0.015748,0.147931,-0.015504,...,0.016483,-0.972920,0.014331,0.590810,-0.017215,0.557246,-0.018433,0.453590,0.134146,8.580442
2,2,0,4,57,20,8,142,0.000440,-0.096282,-0.058896,...,0.009354,0.091455,0.027522,-0.405978,-0.023047,-0.389777,-0.002979,-0.701838,-0.006342,-0.229531
3,3,0,8,1,1,1,2,0.031298,-0.429540,0.007756,...,0.003544,-0.882464,-0.002021,-0.113951,-0.043962,-0.395345,-0.004329,-0.765754,0.014146,-0.593888
4,4,0,14,36,12,5,92,0.027273,-0.847155,-0.039302,...,0.022321,-1.204398,0.018182,-0.879172,-0.026549,-0.858613,-0.017391,-0.029690,-0.008621,-1.022991
5,5,0,23,37,12,5,94,0.010938,-0.238878,0.021548,...,-0.007958,-0.182443,-0.012719,0.014338,-0.002612,-0.424833,-0.042515,1.054858,-0.002851,-0.510536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418590,418590,223,5703,32,10,4,77,0.021843,-0.217823,-0.021703,...,0.001727,-0.026910,0.028785,0.443951,-0.020195,0.523322,-0.008287,-0.305621,0.020077,0.387974
418591,418591,223,5705,35,12,5,91,-0.006920,-0.375251,0.000000,...,0.009226,-0.840418,0.012941,-0.578965,-0.013476,1.214831,0.000000,-0.369791,0.007863,0.017936
418592,418592,223,5709,2,1,1,5,0.021869,-0.978856,-0.005929,...,-0.015826,-0.701318,-0.008824,-0.429746,-0.011628,0.058823,0.024928,-0.103272,0.001890,-0.355770
418593,418593,223,5710,33,10,4,83,0.012248,-0.627169,0.010925,...,0.006752,-0.039305,0.020674,-0.226903,-0.004573,0.056026,0.004594,-0.553728,0.028346,-0.362603
418594,418594,223,5713,26,7,4,60,0.076162,-1.325986,-0.000988,...,0.009782,10.666016,0.012101,-0.533496,-0.004381,0.728943,-0.012973,-0.591195,-0.046392,-0.100896

In [84]:
test.to_csv('x_train_clean.csv')